inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - Gemfile

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Method has too many lines"を無視
Metrics/MethodLength:
  Enabled: false

# "Line is too long"を無視
Layout/LineLength:
  Enabled: false

# "Block has too many lines"を無視(rspecテストのため)
Metrics/BlockLength:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# ブロックコメントを許可（自動生成ファイルのみで使用のため）  
Style/BlockComments:
  Enabled: false

# 文字列のfreeze要求を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Gemfileのアルファベット順記入を無視  
Bundler/OrderedGems:  
  Enabled: false

# ネストしたモジュール/クラス定義の推奨記法を無視（deviseでの自動作成分にて指摘されるため）
Style/ClassAndModuleChildren:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# ハッシュ記法はruby1.9記法で記載
HashSyntax:
  EnforcedStyle: ruby19

# "Specify an :inverse_of option"を無視
Rails/InverseOf:
  Enabled: false

# Windows使用のためローカルではCRLFだがリモートリポジトリではLFに変換されるので無視
Layout/EndOfLine:
  Enabled: false