version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: myportfolio123rubyonrails5@mysqldb
      MYSQL_DATABASE: myfavrest-app_development
      MYSQL_USER: mydev
      MYSQL_PASSWORD: myportfolio123rubyonrails5@mysqldb
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/myapp/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  # test-db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: myportfolio123rubyonrails5@mysqldb
  #     MYSQL_DATABASE: myfavrest-app_test
  #     MYSQL_USER: mydev
  #     MYSQL_PASSWORD: myportfolio123rubyonrails5@mysqldb
  #   ports:
  #     - '3307:3306' # ローカルPCから接続するために設定
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec pumactl start
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
      - sockets:/myapp/tmp/sockets
    privileged: true
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - sockets:/myapp/tmp/sockets
    depends_on: 
      - app
volumes:
  db-volume:
  public-data:
  tmp-data:
  log-data:
  sockets: